// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suytgyzxxyvbnsztwwqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eXRneXp4eHl2Ym5zenR3d3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzOTA2MjIsImV4cCI6MjA3Njk2NjYyMn0.KZKSnH8mkAK4KsxMpLzV6PXgb15mh5akO-ssoH688q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
